jalilms/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        path("", include("web.urls")),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "Jalilms Administration"
admin.site.site_title = "Jalilms Admin Portal"
admin.site.index_title = "Welcome to Jalilms Admin Portal"

web/urls.py
from django.urls import path

from . import views

app_name = "web"

urlpatterns = [
    path("", views.index, name="index"),
    path("about/", views.about, name="about"),
    path("positions/", views.position, name="positions"),
    path("blog/", views.blog, name="blog"),
    path("contact/", views.contact, name="contact"),
    path("email/", views.email, name="email"),
    path("updates/<int:id>", views.updates, name="updates"),
    path("gallery/", views.gallery, name="gallery"),

]

web/models.py
from django import forms
from django.db import models
from django.utils import timezone
from tinymce.models import HTMLField
from versatileimagefield.fields import VersatileImageField


class Update(models.Model):
    image = VersatileImageField(upload_to="blogs")
    date = models.DateField()
    subhead = models.CharField(max_length=20)
    title = models.CharField(max_length=100)
    details = HTMLField()

    def __str__(self):
        return self.title


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    message = models.TextField()
    choices = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Gallery(models.Model):
    image = VersatileImageField(upload_to="gallery")
    name = models.CharField(max_length=30)
    subtitle = models.CharField(max_length=80)

    class Meta:
        verbose_name_plural = "Galleries"

    def __str__(self):
        return self.name


class Email(models.Model):
    email = models.EmailField()

    def __str__(self):
        return str(self.email)


class Notification(models.Model):
    notification = models.subtitle = models.TextField()

    def __str__(self):
        return self.notification


class PositionsToken(models.Model):
    name = models.CharField(max_length=100)
    fromdate = models.DateField(null=True, blank=True)
    toyear = models.CharField(null=True, blank=True,max_length=200)
    subtitle = models.CharField(max_length=80)

    def __str__(self):
        return self.name
    
class Award(models.Model):
    image = VersatileImageField(upload_to="awards")
    name = models.CharField(max_length=100)
    subtitle = models.CharField(max_length=80)

    def __str__(self):
        return self.name


class YoutubeLink(models.Model):
    title = models.CharField(max_length=200)
    video_id = models.CharField(max_length=200)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ("-timestamp",)

    def video_url(self):
        return f"https://youtu.be/{self.video_id}"

web/forms.py
from django import forms
from django.forms import ModelForm
from django.forms import DateInput 
from django.forms.widgets import EmailInput, Textarea, TextInput

from .models import Contact, Email,PositionsToken

CHOICES = [("For Program", "For Program"), ("For Appointment", "For Appointment")]


class ContactForm(forms.ModelForm):
    choices = forms.CharField(
        widget=forms.RadioSelect(choices=CHOICES, attrs={"class": "form-check-input"})
    )

    class Meta:
        model = Contact
        fields = "__all__"

        widgets = {
            "name": forms.TextInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Enter Your Name",
                    "autocomplete": "off",
                }
            ),
            "phone": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "phone"}
            ),
            "email": forms.EmailInput(
                attrs={
                    "class": "form-control ",
                    "placeholder": "Email",
                }
            ),
            "message": forms.Textarea(
                attrs={
                    "class": "form-control ",
                    "placeholder": "Type Your Message",
                }
            ),
        }


class EmailForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = "__all__"

        widgets = {
            "email": forms.EmailInput(
                attrs={
                    "class": "form-control ",
                    "placeholder": "Enter your email address",
                }
            ),
        }



class YearSelectWidget(forms.Select):
    def __init__(self, attrs=None, choices=(), years_from=1990, years_to=2100):
        years = range(years_from, years_to + 1)
        choices = [(year, year) for year in years]
        super().__init__(attrs, choices)

class YearSelectFormField(forms.DateField):
    widget = YearSelectWidget

class PositionsTokenAdminForm(forms.ModelForm):
    class Meta:
        model = PositionsToken
        fields = '__all__'
        widgets = {
            'toyear': YearSelectWidget, 
            'fromdate': DateInput(attrs={'type': 'date'}),
        }

web/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt

from .forms import ContactForm, EmailForm
from .models import Award,PositionsToken, Gallery, Update, YoutubeLink

# Create your views here.


def index(request):
    videos = YoutubeLink.objects.all()[:3]
    gallery = Gallery.objects.all()
    context = {"is_index": True, "videos": videos, "gallery": gallery}
    return render(request, "index.html", context)


def about(request):
    award = Award.objects.all()
    positionsToken = PositionsToken.objects.all()
    context = {"is_about": True, "award": award ,"positionsToken": positionsToken}
    return render(request, "about.html", context)


def position(request):
    context = {"is_position": True}

    return render(request, "positions.html", context)


def blog(request):
    youtube = YoutubeLink.objects.all()
    context = {"is_updates": True, "youtube": youtube}

    return render(request, "blog.html", context)


def updates(request, id):
    update = Update.objects.get(id=id)
    context = {"is_updates": True, "update": update}
    return render(request, "single-blog.html", context)


@csrf_exempt
def contact(request):
    template_name = "contact.html"
    forms = ContactForm(request.POST or None)
    if request.method == "POST":
        if forms.is_valid():
            data = forms.save(commit=False)
            data.referral = "web"
            data.save()
            # return HttpResponse("successfully submitted")
            response_data = {
                "status": "true",
                "title": "Successfully Submitted",
                "message": "Message successfully updated",
            }

        else:
            response_data = {"status": "false", "title": "Form validation error", "message": repr(forms.errors)}
        return HttpResponse(json.dumps(response_data), content_type="application/javascript")
    else:
        context = {"form": forms, "is_contact": True}
    return render(request, template_name, context)


def email(request):
    template_name = "footer.html"
    emailform = EmailForm(request.POST or None)
    if request.method == "POST":
        if emailform.is_valid():
            data = emailform.save(commit=False)
            data.referral = "web"
            data.save()
            return HttpResponse("Successfully subscribed!!!")
        else:
            return HttpResponse("Failed to submit!! form validation error occurred!")
    else:
        context = {"emailform": emailform}
    return render(request, template_name, context)



def gallery(request):
    gallery = Gallery.objects.all()
    context = {"is_gallery": True, "gallery": gallery}
    return render(request, "gallery.html", context)

templates/blog.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<section id="blog_main_page" class="section_padding">

    <div class="container">
        <div class="row">
            {% for i in updates %}
            <div class="col-lg-4 col-md-6 col-sm-12 col-12">
                <div class="blog_area box-shadow">
                    <div class="blog_area_img">
                        <a href="{% url 'web:updates' i.id %}">
                            <img src="{{i.image.url}}" alt="img">
                        </a>
                    </div>
                    <div class="blog_area_text">
                        <p>{{i.subhead}}</p>
                        <h3><a href="{% url 'web:updates' i.id %}">{{i.title}}</a></h3>
                        <div class="blog_flex_area">
                            <p>{{i.date}}</p>

                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>


    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 col-md-12 col-sm-12 col-12">
                <div class="section_title_arae">
                    <h2>Latest Videos</h2>
                </div>
            </div>
        </div>

        <div class="">
            <div class="row">
                {% for video in youtube %}
                <div class="col-xs-12 col-sm-4 p-2">
                    <div class='embed-container'>
                        <iframe src='https://www.youtube.com/embed/{{video.video_id}}' frameborder='0'
                            allowfullscreen></iframe>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
</section>


{% endblock %}

templates/contact.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}

<!-- Contact Area Start -->
<section id="contact_area" class="section_padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 offset-lg-2 col-md-12 col-sm-12 col-12">
        <div class="section_title_arae">
          <h4>Contact</h4>
          <h2>Get In Touch</h2>
        </div>
      </div>
    </div>
    <div class="row">

      <div class="col-lg-6 ">
        <div class="contact_form_main p_absalute border">
          <form method="POST" class="ajax" id="contactForm" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
              {{form.name}}

            </div>
            <div class="form-group">
              {{form.phone}}
            </div>
            <div class="form-group">
              {{form.email}}

            </div>
            <div class="form-group">
              {{form.message}}

            </div>
            <div class="form-check">
              {{form.choices}}
            </div>

            <div class="contact-button" style="margin-top:80px;">
              <button type="submit" class="btn btn-theme">Submit</button>
            </div>
          </form>
          <!-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> -->
        </div>
        <div class="sweet-alert col-lg-12 col-md-6 form-success-result">
          <div class="buttontick">
            <div class="icon success animate">
              <span class="line tip animateSuccessTip"></span>
              <span class="line long animateSuccessLong"></span>
              <span class="placeholder"></span>
              <span class="fix"></span>
            </div>
            <div class="backtohome">
              <a class="btn btn-theme" href="">back to home</a>
            </div>
          </div>
        </div>
      </div>


      <div class="col-lg-6">
        <div class="contact_info_wrapper border mb-3 p_relateve">
          <div class="contact_item">
            <h5>Corporate office address</h5>
            <p> 4th Floor,CD Tower,Near Baby Memorial Hospital,Bypass Road,Calicut - 673004</p>
          </div>
          <div class="contact_item">
            <h5>Office number</h5>
            <p><a href="tel:+918606119888">+91 8606119888</a></p>
            <p><a href="tel:+918606119777">+91 8606119777</a></p>

          </div>
          <div class="contact_item">
            <h5>Mail and Website</h5>
            <p><a href="mailto:guru@careerguruonline.com">guru@careerguruonline.com</a></p>
            <p><a href="mailto:careerguruonline.com"> careerguruonline.com</a></p>
          </div>

        </div>

        <div class="contact_info_wrapper border"
          style="height: 250px;overflow-y: auto;overflow-x: auto;resize: both;position: relative;z-index: 2;overflow:hidden;">
          <iframe style="height:100%;width:100%;border:none;"
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3913.0015897400517!2d75.79041880932937!3d11.261292750019535!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3ba6594fadadd1ab%3A0x23f11cd86fa456f!2sCareer%20Guru!5e0!3m2!1sen!2sin!4v1682751794281!5m2!1sen!2sin"
            style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
        </div>
      </div>
    </div>
  </div>

</section>


{% endblock %}

templates/gallery.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}

<section id="blog_main_page" class="section_padding">

    <div class="container">
        <div class="row">
            {% for i in gallery %}
            <div class="col-lg-4 col-md-6 col-sm-12 col-12">
                <div class="blog_area box-shadow">
                    <div class="blog_area_img">
                        <a href="{% url 'web:updates' i.id %}">
                            <img src="{{i.image.url}}" alt="img">
                            {% comment %} <img src="../../static/web/images/blog/1.jpg" alt="img"> {% endcomment %}
                        </a>
                    </div>
                    {% comment %} <div class="blog_area_text">
                        <p>{{i.subhead}}</p>
                        <h3><a href="{% url 'web:updates' i.id %}">{{i.title}}</a></h3>
                        <div class="blog_flex_area">
                            <p>{{i.date}}</p>

                        </div>
                    </div> {% endcomment %}
                </div>
            </div>
            {% endfor %}

        </div>
    </div>


    {% comment %} <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 col-md-12 col-sm-12 col-12">
                <div class="section_title_arae">
                    <h2>Latest Videos</h2>
                </div>
            </div>
        </div>

        <div class="">
            <div class="row">
                {% for video in youtube %}
                <div class="col-xs-12 col-sm-4 p-2">
                    <div class='embed-container'>
                        <iframe src='https://www.youtube.com/embed/{{video.video_id}}' frameborder='0'
                            allowfullscreen></iframe>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div> {% endcomment %}
</section>


{% endblock %}

templates/index.html
{% extends 'partials/base.html' %}

{% load static %}

{% block content %}

<!-- Who We Are Start -->
<section id="who_we_are_area" class="home_padding">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 col-md-12 col-sm-12 col-12">
                <div class="who_img_area">
                    <img src="{% static 'web/images/add/jaleel_sir.png' %}" alt="img">
                </div>
            </div>
            <div class="col-lg-7 col-md-12 col-sm-12 col-12">
                <div class="who_right_area">
                    <div class="left_align_title">
                        <h2 style="margin-bottom:20px;color:#fa6a45;">Meet, JALIL MS</h2>
                        <h4>Founding CEO & Chief Mentor, Career Guru</h4>

                        <div class="highlite-main">
                            <div class="hero-highlite">
                                <div class="highlite-head">20 +</div>
                                <div class="highlite-sub">Year Experience</div>
                            </div>
                            <div class="hero-highlite">
                                <div class="highlite-head">10 Lakh +</div>
                                <div>Beneficiaries</div>
                            </div>
                            <div class="hero-highlite">
                                <div class="highlite-head">5,000 +</div>
                                <div>Programs</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% include "partials/marquee.html" %}



<section id="joinus_area" class="section_padding bg-custom">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 col-md-12 col-sm-12 col-12">
                <div class="join_text">

                    <h2>Book an appointment</h2>
                    <p>
                        Mr Jalil M S is a renowned career guidance strategist and qualified trainer who spread his wings
                        at both national and international levels. He is also the Managing Director and Chief Career
                        Mentor at Career Guru
                    </p>
                    <a href="{% url 'web:contact' %}" class="btn btn-theme">Get Appointment</a>
                </div>
            </div>
            <div class="col-lg-7 col-md-12 col-sm-12 col-12">
                <div class="join_area_img">
                    <img src="{% static 'web/images/add/Untitled.png' %}" alt="img">
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Updtates Area End-->

<section id="blog_main_page" class="section_padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2 col-md-12 col-sm-12 col-12">
                <div class="section_title_arae">
                    <h2>Latest Videos</h2>
                </div>
            </div>
        </div>
        <div class="row">
            {% for video in videos %}
            <div class="col-xs-12 col-sm-4 p-2">
                <div class='embed-container'>
                    <iframe src='https://www.youtube.com/embed/{{video.video_id}}' frameborder='0'
                        allowfullscreen></iframe>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

{% endblock %}

templates/partials/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- Primary Meta Tags -->
    <title>JALIL MS | Founding CEO & Chief Mentor, Career Guru</title>
    <meta name="title" content="JALIL MS | Founding CEO & Chief Mentor, Career Guru" />
    <meta name="description"
        content="Best qualified trainer and experienced career guidance expert at the National and International levels." />

    <!-- Open Graph / Facebook -->
    <meta property="og:type" content="website" />
    <meta property="og:url" content="https://jalilms.com/" />
    <meta property="og:title" content="JALIL MS | Founding CEO & Chief Mentor, Career Guru" />
    <meta property="og:description"
        content="Best qualified trainer and experienced career guidance expert at the National and International levels." />
    <meta property="og:image" content="https://jalilms.com/static/web/img/preview.png" />

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:url" content="https://jalilms.com/" />
    <meta name="twitter:title" content="JALIL MS | Founding CEO & Chief Mentor, Career Guru" />
    <meta name="twitter:description"
        content="Best qualified trainer and experienced career guidance expert at the National and International levels." />
    <meta name="twitter:image" content="https://jalilms.com/static/web/img/preview.png" />

    <meta property="twitter:card" content="summary_large_image" />
    <meta property="twitter:url" content="https://jalilms.com/" />
    <meta property="twitter:title" content="JALIL MS | Founding CEO & Chief Mentor, Career Guru" />
    <meta property="twitter:description"
        content="Best qualified trainer and experienced career guidance expert at the National and International levels." />
    <meta property="twitter:image" content="https://jalilms.com/static/web/img/preview.png" />

    <link rel="stylesheet" href="{% static 'web/css/bootstrap.min.css' %}?v=1.1" />
    <link rel="stylesheet" href="{% static 'web/css/animate.min.css' %}?v=1.1" />
    <link rel="stylesheet" href="{% static 'web/css/owl.carousel.min.css' %}?v=1.1" />
    <link rel="stylesheet" href="{% static 'web/css/magnific.popup.min.css' %}?v=1.1" />
    <link rel="stylesheet" href="{% static 'web/css/fontawesome.all.min.css' %}?v=1.1" />
    <link rel="stylesheet" href="{% static 'web/css/meanmenu.min.css' %}">
    <link rel="stylesheet" href="{% static 'web/css/color.css' %}?v=1.1" />
    <link rel="stylesheet" href="{% static 'web/css/style.css' %}?v=1.1" />
    <link rel="stylesheet" href="{% static 'web/css/responsive.css' %}?v=1.1" />
    <link rel="stylesheet" href="{% static 'web/css/contact.success.css' %}?v=1.1" />

    <link rel="icon" type="image/png" href="{% static 'web/img/jmsfav.svg' %}?v=1.1" />

</head>

<body>
    {% include "partials/header.html" %}

    {% block content %}

    {% endblock%}

    {% include "partials/footer.html" %}

    <script src="{% static 'web/js/jquery.min.js' %}"></script>
    <script src="{% static 'web/js/popper.min.js' %}"></script>
    <script src="{% static 'web/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'web/js/meanmenu.min.js' %}"></script>
    <script src="{% static 'web/js/magnific.popup.min.js' %}"></script>
    <script src="{% static 'web/js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'web/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'web/js/main.js' %}"></script>
    <script src="{% static 'web/js/ajax.js' %}"></script>
</body>

</html>

templates/partials/footer.html
{% load static %}

<style>
    input#id_email {
        border-radius: 4px 0px 0px 4px;
    }
</style>

<!-- Footer Area Strat -->
<footer id="footer_area">
    <div class="footer_wrapper">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6 col-sm-12 col-12 mx-auto">
                    <div class="footer_wedget text-center">
                        <div class="footer_heading">
                            <h4>SUBSCRIBE NEWSLETTER</h4>
                        </div>
                        <div class="footerSubscribe">
                            <form action="/email/" method="POST" class="footer_sub input-group">
                                {% csrf_token %}
                                <!-- <input type="text" class="form-control" placeholder="Enter your email address"> -->
                                {{emailform.email}}
                                <button type="submit"> <i class="fa fa-envelope" aria-hidden="true"></i> </button>
                            </form>
                            <div class="footer_soical_link">
                                <p>Get In Touch.</p>
                                <ul class="footer_icons">
                                    <li><a href="http://facebook.com/careergurujalil" target="_blank"><i
                                                class="fab facebook fa-facebook-f"></i></a></li>
                                    <li><a href="https://youtube.com/@CareerGuruOnlineChannel"><i
                                                class="fab youtube fa-youtube"></i></a></li>
                                    <li><a href="https://www.instagram.com/jalilmadambat/?igshid=YmMyMTA2M2Y%3D"
                                            target="_blank"><i class="fab instagram fa-instagram"></i></a></li>
                                    <li><a href="https://www.linkedin.com/in/jalil-ms-74182b7/?originalSubdomain=in"
                                            target="_blank"><i class="fab linkedin fa-linkedin-in"></i></a></li>
                                </ul>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>


<div id="copy_right_area" class="bg-custom">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="copy_right_text">
                    <p>@ {% now 'Y' %} - Gedexo | All Rights Reserved</p>
                </div>
            </div>
        </div>
    </div>
</div>


<div class="float_icon">
    <a href="https://t.me/+E6atd8VXwJo3ZDRl" class="d-inline-block" target="_blank">
        <span>Join Telegram Community</span>
        <img src="{% static 'web/img/telegram.png' %}" alt="">
    </a>
</div>

templates/partials/header.html
{% load static %}

<header class="header-area shadow">
    <!-- Start Navbar Area -->
    <div class="navbar-area">
        <div class="cmo-responsive-nav">
            <div class="container">
                <div class="cmo-responsive-menu">
                    <div class="logo">
                        <a href="{% url 'web:index' %}">
                            <img src="{% static 'web/img/logo/jmslogo.svg' %}" alt="logo">
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <div class="cmo-nav">
            <div class="container">
                <nav class="navbar navbar-expand-md navbar-light">
                    <a class="navbar-brand" href="{% url 'web:index' %}">
                        <img src="{% static 'web/img/logo/jmslogo.svg' %}" alt="logo">
                    </a>

                    <div class="collapse navbar-collapse mean-menu">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a href="{% url 'web:index' %}" class="nav-link  {% if is_index %} active {% endif %}">
                                    Home
                                </a>
                            </li>

                            <li class="nav-item">
                                <a href="{% url 'web:about' %}" class="nav-link {% if is_about %} active {% endif %}">
                                    Profile
                                </a>
                            </li>

                            {% comment %} <li class="nav-item">
                                <a href="{% url 'web:positions' %}"
                                    class="nav-link {% if is_position %} active {% endif %}">
                                    Positions</i>
                                </a>
                            </li> {% endcomment %}


                            <li class="nav-item">
                                <a href="{% url 'web:blog' %}" class="nav-link {% if is_updates %} active {% endif %}">Blog</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'web:gallery' %}" class="nav-link {% if is_gallery %} active {% endif %}">gallery</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'web:contact' %}"
                                    class="nav-link {% if is_contact %} active {% endif %}">
                                    Connect
                                </a>

                            </li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
    <!-- End Navbar Area -->

</header>

templates/partials/marquee.html
<div class="top-header">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-12">
                <div class="d-flex text-white flex-nowrap align-items-center">
                    <span class="heading">Career Notifications:</span>
                    <marquee class="marquee" scrollamount="6">
                        {% for notification in notification %}
                        <span class="item">{{notification.notification}}</span>
                        {% endfor %}
                    </marquee>
                </div>
            </div>
        </div>
    </div>
</div>

templates/single-blog.html
{% extends 'partials/base.html' %}
{% load static %}

{% block content %}
<section id="blog_main_page" class="section_padding">
   <div class="container">
      <div class="row">
         <div class="col-lg-12">
            <div class="single_blog_wrappers">
               <div class="blog_single_item  box-shadow">
                  <div class="blog_single_text_area">
                     <div class="blog_single_top_img" style="justify-content:center;text-align:center;">
                        <img src="{{update.image.url}}" alt="img">
                     </div>
                     <div class="blog_single_viewer_area ">
                        <ul>
                           <li><a href="#!"><i class="far fa-user"></i> {{update.subhead}}</a></li>
                           <li><a href="#!"><i class="far fa-clock"></i> {{update.date}}</a></li>
                           <!-- <li><a href="#!"><i class="far fa-comment"></i> 4</a></li> -->
                        </ul>
                     </div>
                     <div class="blog_single_heading">
                        <h3>{{update.title}}.</h3>
                     </div>
                     <div class="blog_single_text">
                        <p>{{update.details|safe}}</p>

                     </div>

                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>

{% endblock %}